import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
    returnView1 : {
      width: '100%',
      backgroundColor: '#e5e5e5',
      flex: 1,
    },
    renderView:{
      backgroundColor: '#e5e5e5',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 5,
      borderWidth: 3,
      borderColor: 'black',
      borderRadius: 5,
    },
    renderViewHeader:{
      flexDirection: 'row',
      alignItems:'center',
      width: '80%'
    },
    renderDevicesName:{
      fontSize: 22,
      fontWeight: '800',
      color: '#2d75ac',
      padding: 10,
      width:'90%',
      textAlign:'center',
    },
    renderviewChart:{
      flexDirection: 'row',
      backgroundColor: 'black',
      padding: 10,
      width: '90%',
      borderRadius: 10,
      justifyContent: 'space-evenly',
    },
    rendertext1:{
      fontSize: 15,
      fontWeight: '500',
      marginTop: 5,
      marginBottom: 5,
      padding: 8,
      width: '90%',
      borderBottomWidth: 1,
      borderBottomColor: 'black',
      borderRadius: 10,
      color: 'black',
    } ,
    rendertext2:{
      fontSize: 15,
      fontWeight: '500',
      marginTop: 5,
      marginBottom: 5,
      padding: 8,
      width: '90%',
      borderWidth: 1,
      borderColor: 'red',
      borderRadius: 10,
      color: 'black',
    } ,
    buttonAdd: {
        justifyContent:'center',
        alignItems:'center',
        position:'absolute',
        bottom:120,
        right:30,
        borderRadius:50,
      },
      InputAdd: {
        backgroundColor:'#fff',
        width:'90%',
        height:50,
        borderRadius:10,
        borderWidth:1,
        shadowOffset: { height: 5, width: 1 },
        shadowOpacity:1,
        shadowRadius:20,
        shadowColor:'black',
        elevation:5,
        paddingLeft:20,
      },
      box :   {
        width:300,
        height:180,
        position:'absolute',
        alignItems:'center',
        paddingTop:15,
        borderRadius:10,
        shadowOffset: { height: 5, width: 1 },
        shadowOpacity:1,
        shadowRadius:20,
        backgroundColor:'#fff',
        shadowColor:'black',
        elevation:15,
      },
      buttonadd_delete: {
        height:'30%',
        width:'35%',
        position:'absolute',
        bottom:30,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:10,
        shadowOffset: { height: 5, width: 1 },
        shadowOpacity:1,
        shadowRadius:20,
        backgroundColor:'white',
        elevation:15,
      },

});
